ALTER TYPE "EmailTemplateEvent" ADD VALUE 'SERVICE_REQUEST_CREATED_CUSTOMER';
ALTER TYPE "EmailTemplateEvent" ADD VALUE 'SERVICE_REQUEST_CREATED_STAFF';
ALTER TYPE "EmailTemplateEvent" ADD VALUE 'SERVICE_REQUEST_ASSIGNED';
ALTER TYPE "EmailTemplateEvent" ADD VALUE 'SERVICE_REQUEST_STATUS_CHANGED';
