import { Activity, AlertTriangle, ArrowRight, Bot, CheckCircle2, Clock3, Coins, Cpu, ShieldCheck, Wrench, X } from "lucide-react";
import { useState } from "react";
import { useAdminAiMetrics, useAdminAiRuns } from "../features/ai/aiQueries.js";
import { formatStayDate } from "../features/customer/customerQueries.js";

const number = new Intl.NumberFormat("en-NG");
const duration = (value) => value === null ? "—" : value >= 1000 ? `${(value / 1000).toFixed(1)}s` : `${value}ms`;

export function AdminAiInsightsPage() {
  const [days, setDays] = useState(7);
  const [runStatus, setRunStatus] = useState("");
  const [selectedRun, setSelectedRun] = useState(null);
  const { data, isPending, error, refetch, isFetching } = useAdminAiMetrics(days);
  const { data: runs = [], isPending: runsPending, error: runsError } = useAdminAiRuns({ limit: 50, status: runStatus });
  if (isPending) return <div className="admin-screen admin-loading">Reading AI telemetry…</div>;
  if (error) return <div className="admin-screen"><div className="form-error">{error.message}</div></div>;
  const tokens = data.totals.tokens.totalTokens || 0;
  const pending = Object.entries(data.pendingActions).filter(([, count]) => count > 0);
  const maxToolRuns = Math.max(...data.tools.map((tool) => tool.runs), 1);

  return <main className="admin-screen ai-insights-screen">
    <div className="admin-heading"><div><span className="eyebrow">AI operations</span><h1>Concierge intelligence</h1><p>Monitor Gemini reliability, speed, tool activity, and protected guest actions without exposing private conversations.</p></div><div className="ai-period-control"><label><span>Reporting window</span><select value={days} onChange={(event) => setDays(Number(event.target.value))}>{[1, 7, 30, 90].map((value) => <option key={value} value={value}>Last {value} {value === 1 ? "day" : "days"}</option>)}</select></label><button className="admin-refresh" onClick={() => refetch()} disabled={isFetching}>{isFetching ? "Refreshing…" : "Refresh"}</button></div></div>
    <section className="ai-health-banner"><div><span><ShieldCheck /> Operational telemetry</span><h2>{data.totals.successRate >= 95 ? "The concierge is performing reliably." : data.totals.runs ? "The concierge needs attention." : "Waiting for concierge activity."}</h2><p>Since {formatStayDate(data.period.since)} · Gemini provider</p></div><strong>{data.totals.successRate}%<small>success rate</small></strong></section>
    <section className="admin-kpis ai-kpis"><article><span><Activity /> Total runs</span><strong>{number.format(data.totals.runs)}</strong><small>{data.totals.processing} currently processing</small></article><article><span><CheckCircle2 /> Successful</span><strong>{number.format(data.totals.succeeded)}</strong><small>{data.totals.failed} failed run{data.totals.failed === 1 ? "" : "s"}</small></article><article><span><Clock3 /> Average latency</span><strong>{duration(data.totals.averageDurationMs)}</strong><small>End-to-end model response</small></article><article><span><Coins /> Tokens used</span><strong>{number.format(tokens)}</strong><small>{number.format(data.totals.tokens.inputTokens || 0)} input · {number.format(data.totals.tokens.outputTokens || 0)} output</small></article></section>
    <section className="ai-insights-grid"><article className="admin-panel ai-tools-panel"><header><div><Wrench /><span><strong>Tool activity</strong><small>Functions selected by the concierge</small></span></div></header><div>{data.tools.map((tool) => <section key={tool.name}><div><span>{tool.name.replaceAll("_", " ")}</span><strong>{tool.runs}</strong></div><i><b style={{ width: `${(tool.runs / maxToolRuns) * 100}%` }} /></i></section>)}{!data.tools.length && <p className="admin-empty-line">No tool calls in this period.</p>}</div></article><article className="admin-panel ai-actions-panel"><header><div><Bot /><span><strong>Protected actions</strong><small>Confirmation lifecycle across all time</small></span></div></header><div>{pending.map(([status, count]) => <span key={status}><i className={status.toLowerCase()} />{status.replaceAll("_", " ")}<strong>{count}</strong></span>)}{!pending.length && <p className="admin-empty-line">No protected actions recorded.</p>}</div></article></section>
    <section className="admin-panel ai-error-panel"><header><div><AlertTriangle /><span><strong>Recent failures</strong><small>Latest provider and orchestration error codes</small></span></div></header><div>{data.recentErrors.map((item) => <article key={item.id}><span className="status-pill failed">Failed</span><div><strong>{item.errorCode || "UNCLASSIFIED_ERROR"}</strong><small>{item.provider} · {item.model}</small></div><span>{duration(item.durationMs)}</span><time>{formatStayDate(item.createdAt, { hour: "numeric", minute: "2-digit" })}</time></article>)}{!data.recentErrors.length && <p className="admin-empty-line">No AI failures in this reporting window.</p>}</div></section>
    <section className="ai-run-section"><header><div><span className="eyebrow">Run diagnostics</span><h2>Recent AI runs</h2><p>Operational metadata only. Guest prompts and responses are never displayed.</p></div><label><span>Status</span><select value={runStatus} onChange={(event) => setRunStatus(event.target.value)}><option value="">All statuses</option>{["SUCCEEDED", "FAILED", "PROCESSING"].map((status) => <option key={status}>{status}</option>)}</select></label></header>{runsPending && <div className="admin-loading">Loading AI runs…</div>}{runsError && <div className="form-error">{runsError.message}</div>}<div className="admin-table-wrap"><table className="admin-table ai-runs-table"><thead><tr><th>Status</th><th>Model</th><th>Response</th><th>Tool</th><th>Duration</th><th>Tokens</th><th>Started</th><th /></tr></thead><tbody>{runs.map((run) => <tr key={run.id}><td><span className={`status-pill ${run.status.toLowerCase()}`}>{run.status}</span></td><td><strong>{run.model}</strong><small>{run.provider}</small></td><td><strong>{run.responseType?.replaceAll("_", " ") || "—"}</strong><small>{run.confirmationRequired ? "Confirmation required" : "No confirmation"}</small></td><td><strong>{run.toolName?.replaceAll("_", " ") || "No tool"}</strong></td><td><strong>{duration(run.durationMs)}</strong></td><td><strong>{run.totalTokens === null ? "—" : number.format(run.totalTokens)}</strong></td><td><strong>{formatStayDate(run.createdAt, { hour: "numeric", minute: "2-digit" })}</strong></td><td><button onClick={() => setSelectedRun(run)} aria-label={`Inspect run ${run.id}`}><ArrowRight /></button></td></tr>)}</tbody></table>{!runsPending && !runs.length && <div className="admin-table-empty"><Cpu /><p>No AI runs match this status.</p></div>}</div></section>
    {selectedRun && <div className="admin-drawer-shade"><aside className="admin-drawer ai-run-drawer"><header><div><span className="eyebrow">Run diagnostic</span><h2>{selectedRun.status.toLowerCase()}</h2></div><button onClick={() => setSelectedRun(null)} aria-label="Close diagnostic"><X /></button></header><div className="ai-run-identity"><small>Run identifier</small><strong>{selectedRun.id}</strong></div><dl>{[["Provider", selectedRun.provider], ["Model", selectedRun.model], ["Response type", selectedRun.responseType?.replaceAll("_", " ") || "—"], ["Tool selected", selectedRun.toolName?.replaceAll("_", " ") || "No tool"], ["Confirmation", selectedRun.confirmationRequired ? "Required" : "Not required"], ["Duration", duration(selectedRun.durationMs)], ["Input tokens", selectedRun.inputTokens ?? "—"], ["Output tokens", selectedRun.outputTokens ?? "—"], ["Total tokens", selectedRun.totalTokens ?? "—"], ["Started", formatStayDate(selectedRun.createdAt, { hour: "numeric", minute: "2-digit" })], ["Completed", selectedRun.completedAt ? formatStayDate(selectedRun.completedAt, { hour: "numeric", minute: "2-digit" }) : "In progress"]].map(([term, value]) => <div key={term}><dt>{term}</dt><dd>{value}</dd></div>)}</dl>{selectedRun.errorCode && <section className="ai-run-error"><AlertTriangle /><div><small>Error code</small><strong>{selectedRun.errorCode}</strong></div></section>}<p className="drawer-note"><ShieldCheck /> Privacy boundary active: this diagnostic intentionally excludes the guest’s identity, prompt, and model response.</p></aside></div>}
  </main>;
}
