import { useMutation, useQueryClient } from "@tanstack/react-query";
import { ArrowDown, ArrowUp, BedDouble, Check, ImagePlus, Pencil, Plus, Search, Star, Trash2, X } from "lucide-react";
import { useMemo, useState } from "react";
import { useAdminRooms } from "../features/admin/adminQueries.js";
import { useAuth } from "../features/auth/authContext.js";
import { useRoomTypeImages, useRoomTypes } from "../features/rooms/roomQueries.js";
import { formatNaira } from "../features/rooms/roomCatalog.js";
import { api } from "../lib/api.js";

const statuses = ["AVAILABLE", "MAINTENANCE", "OUT_OF_SERVICE"];

function RoomEditor({ room, roomTypes, onClose }) {
  const queryClient = useQueryClient();
  const [form, setForm] = useState({ roomNumber: room?.roomNumber || "", roomTypeId: room?.roomTypeId || roomTypes[0]?.id || "", status: room?.status || "AVAILABLE" });
  const save = useMutation({ mutationFn: () => room ? api.patch(`/api/rooms/${room.id}`, form) : api.post("/api/rooms/create", form), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ["admin-rooms"] }); queryClient.invalidateQueries({ queryKey: ["management-dashboard"] }); onClose(); } });
  const update = (event) => setForm((current) => ({ ...current, [event.target.name]: event.target.value }));
  const options = room?.status === "OCCUPIED" ? ["OCCUPIED"] : statuses;
  return <div className="admin-drawer-shade" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><form className="admin-drawer" onSubmit={(event) => { event.preventDefault(); save.mutate(); }}><header><div><span className="eyebrow">Inventory record</span><h2>{room ? `Edit room ${room.roomNumber}` : "Add a room"}</h2></div><button type="button" onClick={onClose}><X /></button></header><label><span>Room number</span><input name="roomNumber" value={form.roomNumber} onChange={update} required disabled={room?.status === "OCCUPIED"} /></label><label><span>Room type</span><select name="roomTypeId" value={form.roomTypeId} onChange={update} required disabled={room?.status === "OCCUPIED"}>{roomTypes.map((type) => <option value={type.id} key={type.id}>{type.name}</option>)}</select></label><label><span>Operational status</span><select name="status" value={form.status} onChange={update} disabled={room?.status === "OCCUPIED"}>{options.map((status) => <option key={status}>{status}</option>)}</select></label>{room?.status === "OCCUPIED" && <p className="drawer-note">This room is controlled by an active stay. Check the guest out from Reservations before editing it.</p>}{save.error && <div className="form-error">{save.error.message}</div>}<button className="button dark full" disabled={save.isPending || room?.status === "OCCUPIED"}>{save.isPending ? "Saving…" : "Save room"}</button></form></div>;
}

function RoomTypeManager({ roomType, onClose }) {
  const queryClient = useQueryClient();
  const { data: images = [] } = useRoomTypeImages(roomType.id);
  const [form, setForm] = useState({ description: roomType.description || "", capacity: roomType.capacity, pricePerNight: roomType.pricePerNight });
  const refresh = () => { queryClient.invalidateQueries({ queryKey: ["room-types"] }); queryClient.invalidateQueries({ queryKey: ["room-type-images", roomType.id] }); };
  const updateType = useMutation({ mutationFn: () => api.patch(`/api/room-types/${roomType.id}`, form), onSuccess: refresh });
  const upload = useMutation({ mutationFn: (files) => { const body = new FormData(); [...files].forEach((file) => body.append("images", file)); body.append("altText", `${roomType.name.toLowerCase()} hotel room`); return api.post(`/api/room-types/${roomType.id}/images`, body); }, onSuccess: refresh });
  const primary = useMutation({ mutationFn: (id) => api.patch(`/api/room-types/${roomType.id}/images/${id}/primary`), onSuccess: refresh });
  const remove = useMutation({ mutationFn: (id) => api.delete(`/api/room-types/${roomType.id}/images/${id}`), onSuccess: refresh });
  const reorder = useMutation({ mutationFn: (ids) => api.patch(`/api/room-types/${roomType.id}/images/reorder`, { imageIds: ids }), onSuccess: refresh });
  const move = (index, direction) => { const target = index + direction; if (target < 0 || target >= images.length) return; const ids = images.map(({ id }) => id); [ids[index], ids[target]] = [ids[target], ids[index]]; reorder.mutate(ids); };
  const actionError = updateType.error || upload.error || primary.error || remove.error || reorder.error;
  return <div className="admin-drawer-shade"><div className="admin-drawer room-type-drawer"><header><div><span className="eyebrow">Room category</span><h2>{roomType.name.toLowerCase()}</h2></div><button onClick={onClose}><X /></button></header><form onSubmit={(event) => { event.preventDefault(); updateType.mutate(); }}><label><span>Description</span><textarea value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /></label><div><label><span>Capacity</span><input type="number" min="1" value={form.capacity} onChange={(event) => setForm({ ...form, capacity: Number(event.target.value) })} /></label><label><span>Nightly rate (NGN)</span><input type="number" min="1" step="0.01" value={form.pricePerNight} onChange={(event) => setForm({ ...form, pricePerNight: event.target.value })} /></label></div><button className="button dark" disabled={updateType.isPending}><Check /> Save details</button></form><section className="image-manager"><header><div><strong>Gallery</strong><small>{images.length} images · first image leads the gallery</small></div><label><ImagePlus /> Upload<input type="file" multiple accept="image/jpeg,image/png,image/webp,image/gif,image/avif" onChange={(event) => event.target.files.length && upload.mutate(event.target.files)} /></label></header><div>{images.map((image, index) => <article key={image.id}><img src={image.url} alt={image.altText || roomType.name} /><span>{image.isPrimary && <i><Star /> Primary</i>}<button title="Move earlier" onClick={() => move(index, -1)} disabled={index === 0 || reorder.isPending}><ArrowUp /></button><button title="Move later" onClick={() => move(index, 1)} disabled={index === images.length - 1 || reorder.isPending}><ArrowDown /></button>{!image.isPrimary && <button title="Make primary" onClick={() => primary.mutate(image.id)}><Star /></button>}<button title="Delete image" onClick={() => window.confirm("Delete this gallery image permanently?") && remove.mutate(image.id)}><Trash2 /></button></span></article>)}</div></section>{actionError && <div className="form-error">{actionError.message}</div>}</div></div>;
}

export function AdminRoomsPage() {
  const { user } = useAuth();
  const canManage = user.roles.some((role) => ["SUPER_ADMIN", "ADMIN"].includes(role));
  const { data: rooms = [], isPending, error } = useAdminRooms();
  const { data: roomTypes = [] } = useRoomTypes();
  const queryClient = useQueryClient();
  const [search, setSearch] = useState(""); const [status, setStatus] = useState(""); const [editor, setEditor] = useState(null); const [typeEditor, setTypeEditor] = useState(null);
  const visible = useMemo(() => rooms.filter((room) => (!status || room.status === status) && (!search.trim() || `${room.roomNumber} ${room.roomType.name}`.toLowerCase().includes(search.toLowerCase()))), [rooms, search, status]);
  const remove = useMutation({ mutationFn: (id) => api.delete(`/api/rooms/${id}`), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ["admin-rooms"] }); queryClient.invalidateQueries({ queryKey: ["management-dashboard"] }); } });
  return <main className="admin-screen"><div className="admin-heading"><div><span className="eyebrow">House inventory</span><h1>Rooms & categories</h1><p>Keep room availability, rates, capacity, and guest-facing imagery accurate.</p></div>{canManage && <button className="button dark" onClick={() => setEditor("new")}><Plus /> Add room</button>}</div><section className="room-type-admin-grid">{roomTypes.map((type) => { const count = rooms.filter((room) => room.roomTypeId === type.id).length; return <article key={type.id}><div><span>{type.name}</span><strong>{formatNaira(type.pricePerNight)}</strong><small>per night · {type.capacity} guests · {count} rooms</small></div>{canManage && <button onClick={() => setTypeEditor(type)}><Pencil /> Manage category</button>}</article>; })}</section><section className="admin-filters room-filters"><label className="admin-search"><Search /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Room number or category" /></label><label><span>Status</span><select value={status} onChange={(event) => setStatus(event.target.value)}><option value="">All room states</option>{["AVAILABLE", "OCCUPIED", "MAINTENANCE", "OUT_OF_SERVICE"].map((item) => <option key={item}>{item}</option>)}</select></label></section>{isPending && <div className="admin-loading">Counting every key…</div>}{error && <div className="form-error">{error.message}</div>}<section className="room-inventory-grid">{visible.map((room) => <article key={room.id}><header><span>Room</span><strong>{room.roomNumber}</strong></header><div><span className={`room-state-pill ${room.status.toLowerCase()}`}>{room.status.replaceAll("_", " ")}</span><h2>{room.roomType.name.toLowerCase()}</h2><small>{formatNaira(room.roomType.pricePerNight)} · up to {room.roomType.capacity} guests</small></div>{canManage && <footer><button onClick={() => setEditor(room)}><Pencil /> Edit</button><button onClick={() => window.confirm(`Delete room ${room.roomNumber}? This cannot be undone.`) && remove.mutate(room.id)} title="Deletion is blocked when reservation history exists"><Trash2 /> Delete</button></footer>}</article>)}</section>{!isPending && !visible.length && <div className="admin-table-empty"><BedDouble /><p>No rooms match this view.</p></div>}{remove.error && <div className="form-error floating-error">{remove.error.message}</div>}{editor && <RoomEditor room={editor === "new" ? null : editor} roomTypes={roomTypes} onClose={() => setEditor(null)} />}{typeEditor && <RoomTypeManager roomType={typeEditor} onClose={() => setTypeEditor(null)} />}</main>;
}
