import { useMutation, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, ArrowRight, CheckCircle2, Copy, Mail, Plus, Search, Users, X } from "lucide-react";
import { useState } from "react";
import { Link } from "react-router";
import { useAdminStaff, useStaffRoles } from "../features/admin/adminQueries.js";
import { formatStayDate } from "../features/customer/customerQueries.js";
import { api } from "../lib/api.js";

function createTemporaryPassword() {
  const bytes = crypto.getRandomValues(new Uint32Array(3));
  return `Au!${[...bytes].map((value) => value.toString(36)).join("").slice(0, 13)}9`;
}

function StaffCreator({ roles, onClose }) {
  const queryClient = useQueryClient();
  const [form, setForm] = useState({ firstName: "", lastName: "", email: "", phone: "", password: createTemporaryPassword(), roles: [] });
  const [created, setCreated] = useState(null);
  const create = useMutation({ mutationFn: () => api.post("/api/management/staff", { ...form, phone: form.phone || null }), onSuccess: ({ data, message }) => { setCreated({ ...data, message, temporaryPassword: form.password }); queryClient.invalidateQueries({ queryKey: ["admin-staff"] }); } });
  const update = (event) => setForm((current) => ({ ...current, [event.target.name]: event.target.value }));
  const toggleRole = (name) => setForm((current) => ({ ...current, roles: current.roles.includes(name) ? current.roles.filter((role) => role !== name) : [...current.roles, name] }));
  if (created) return <div className="admin-drawer-shade"><div className="admin-drawer staff-created"><header><div><span className="eyebrow">Account created</span><h2>{created.firstName} is ready</h2></div><button onClick={onClose}><X /></button></header><CheckCircle2 /><h3>{created.onboardingEmail.status === "SENT" ? "Onboarding email sent" : "Email delivery failed"}</h3><p>{created.message}</p><div><small>Temporary password — provide this separately and securely</small><strong>{created.temporaryPassword}</strong><button onClick={() => navigator.clipboard.writeText(created.temporaryPassword)}><Copy /> Copy password</button></div><button className="button dark full" onClick={onClose}>Done</button></div></div>;
  return <div className="admin-drawer-shade"><form className="admin-drawer staff-creator" onSubmit={(event) => { event.preventDefault(); create.mutate(); }}><header><div><span className="eyebrow">Secure onboarding</span><h2>Add a staff member</h2></div><button type="button" onClick={onClose}><X /></button></header><div className="drawer-two"><label><span>First name</span><input name="firstName" value={form.firstName} onChange={update} required /></label><label><span>Last name</span><input name="lastName" value={form.lastName} onChange={update} required /></label></div><label><span>Email</span><input name="email" type="email" value={form.email} onChange={update} required /></label><label><span>Phone (optional)</span><input name="phone" value={form.phone} onChange={update} /></label><label><span>Temporary password</span><div className="generated-password"><input name="password" value={form.password} onChange={update} minLength="8" required /><button type="button" onClick={() => setForm({ ...form, password: createTemporaryPassword() })}>Regenerate</button></div></label><fieldset><legend>Assigned roles</legend>{roles.map((role) => <label key={role.name}><input type="checkbox" checked={form.roles.includes(role.name)} onChange={() => toggleRole(role.name)} /><span><strong>{role.name.replaceAll("_", " ")}</strong><small>{role.description || "Hotel administration permission"}</small></span></label>)}</fieldset><p className="drawer-note"><Mail /> The onboarding email contains the portal link and roles, never the temporary password. Share the password through a separate secure channel.</p>{create.error && <div className="form-error">{create.error.message}</div>}<button className="button dark full" disabled={create.isPending || !form.roles.length}>{create.isPending ? "Creating account…" : "Create staff account"}</button></form></div>;
}

export function AdminStaffPage() {
  const [filters, setFilters] = useState({ search: "", role: "", page: 1, limit: 20 }); const [creating, setCreating] = useState(false);
  const { data, isPending, error } = useAdminStaff(filters); const { data: roles = [] } = useStaffRoles();
  const staff = data?.staff || []; const pagination = data?.pagination;
  return <main className="admin-screen"><div className="admin-heading"><div><span className="eyebrow">Super Admin control</span><h1>Staff & roles</h1><p>Onboard the team and keep every account aligned with least-privilege access.</p></div><button className="button dark" onClick={() => setCreating(true)}><Plus /> Add staff</button></div><section className="admin-filters staff-filters"><label className="admin-search"><Search /><input value={filters.search} onChange={(event) => setFilters({ ...filters, search: event.target.value, page: 1 })} placeholder="Search name or email" /></label><label><span>Role</span><select value={filters.role} onChange={(event) => setFilters({ ...filters, role: event.target.value, page: 1 })}><option value="">All staff roles</option>{roles.map((role) => <option value={role.name} key={role.name}>{role.name.replaceAll("_", " ")}</option>)}</select></label></section>{isPending && <div className="admin-loading">Loading the team…</div>}{error && <div className="form-error">{error.message}</div>}<section className="staff-grid">{staff.map((person) => <Link to={`/admin/staff/${person.id}`} key={person.id}><div className="staff-avatar">{person.firstName[0]}{person.lastName[0]}</div><div><span className={`staff-status ${person.status.toLowerCase()}`}>{person.status}</span><h2>{person.firstName} {person.lastName}</h2><p>{person.email}</p><div>{person.roles.map((role) => <small key={role.name}>{role.name.replaceAll("_", " ")}</small>)}</div><time>Joined {formatStayDate(person.createdAt)}</time></div><ArrowRight /></Link>)}</section>{!isPending && !staff.length && <div className="admin-table-empty"><Users /><p>No staff accounts match this view.</p></div>}{pagination?.pages > 1 && <nav className="admin-pagination"><button disabled={pagination.page <= 1} onClick={() => setFilters({ ...filters, page: filters.page - 1 })}><ArrowLeft /> Previous</button><span>Page {pagination.page} of {pagination.pages}</span><button disabled={pagination.page >= pagination.pages} onClick={() => setFilters({ ...filters, page: filters.page + 1 })}>Next <ArrowRight /></button></nav>}{creating && <StaffCreator roles={roles} onClose={() => setCreating(false)} />}</main>;
}
